services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Secret123!
      POSTGRES_DB: UniversityDb
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - university_network

volumes:
    postgres_volume:
networks:
  university_network:
    driver: bridge